### ISSUE TITLE
Waybar icons are badly formatted

### ISSUE THREAD

**Issue by curtisy1** [peux-os-sic/Peux-wayfire-22#1]
Really love the dotfiles you made! I'm currently using them on Fedora and they're working very well.

A small thing I noticed though is that the icons used for waybar seem to be broken. All I'm seeing is a few . This also seems to be the case for other editions using waybar

**Comment by DN-debug** [comment]
> Really love the dotfiles you made! I'm currently using them on Fedora and they're working very well.
> 
> A small thing I noticed though is that the icons used for waybar seem to be broken. All I'm seeing is a few . This also seems to be the case for other editions using waybar

Hey!!

That issue could be due to the missing fonts. I might have missed to add font-awesome and material-fonts in the dots.

**Comment by curtisy1** [comment]
Yup, that was it. It's working fine now, thanks for your help!
